default_config: False
send_base_config: False
send_imish_config: True
# Primary F5
f5_primary:
  host: 10.240.72.161
# Secondary F5
f5_secondary:
  host: 10.240.72.162
user:
  username: admin
  password: admin
ixload: 10.244.24.23