# Set the F5s to the default configuration
default_config: False

# Send the tmsh configuration found in f5_primary/f5_secondary.tmsh
send_base_config: False

# Send imish/bgp configuration commands for ZebOS
send_imish_config: False

# Primary F5
f5_primary:
  host: 10.240.72.161
# Secondary F5
f5_secondary:
  host: 10.240.72.162

# Web credentials
user:
  username: admin
  password: admin

# ixnetwork configuration
ixnetwork:
  name:               'ixia'
  api_server_ip:      '172.22.73.14'
  tcl_port:           8010
  chassis_ip:         10.244.24.23
  port_list:          [('10.244.244.23', 11, 1), ('10.244.24.23', 11, 2)]
  ixnetwork_version:  8.5
  license_server_ip:  10.244.24.23

# ixload configuration
ixload:
  site_url:           'http://172.22.73.14:8080/api/v0/'
  port_list:          [('10.244.244.23', 11, 1), ('10.244.24.23', 11, 2)]
  ixload_version:     8.50.0.465