# Set the F5s to the default configuration
default_config: False

# Send the tmsh configuration found in f5_primary/f5_secondary.tmsh
send_base_config: False

# Send imish/bgp configuration commands for ZebOS
send_imish_config: False

# Primary F5
f5_primary:
  host: 10.240.72.161
# Secondary F5
f5_secondary:
  host: 10.240.72.162

# Web credentials
user:
  username: admin
  password: admin

ixload: 10.244.24.23