pool:                   'http_test_pool'
virtual_server:         '198.18.32.1'
v6_pool:                'v6_http_test_pool'
v6_virtual_server:      'v6_test_virtual_server'
v6_virtual_server_ip:   '2001:200:0:1200::1'
v6_nodes:               ['2001:200:0:1300::10','2001:200:0:1300::11']
v6_node_1:              '2001:200:0:1300::10'
v6_node_2:              '2001:200:0:1300::11'
nodes:                  ['198.18.64.11','198.18.64.12']
node_1:                 '198.18.64.11'
node_2:                 '198.18.64.12'

# AFM Variables
test_domain:            'qa.com'
dns_server_1:           '198.18.64.11'
dns_server_2:           '198.18.64.12'
v6_dns_server_1:        '2001:200::1300:0:0:0:100'
v6_dns_server_2:        '2001:200::1300:0:0:0:101'